# Generated by Django 5.2.1 on 2025-07-03 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_customuser_address_customuser_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontendPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome da Permissão')),
                ('codename', models.CharField(max_length=100, unique=True, verbose_name='Codename (identificador da seção)')),
            ],
            options={
                'verbose_name': 'Permissão do Painel',
                'verbose_name_plural': 'Permissões do Painel',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='cargo',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='users.frontendpermission', verbose_name='Permissões no Painel'),
        ),
    ]
