# Generated by Django 5.2.1 on 2025-06-01 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='stock_images/', verbose_name='Foto do Item'),
        ),
    ]
