# Generated by Django 5.2.1 on 2025-06-01 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_stockitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Validade'),
        ),
    ]
