# Generated by Django 5.2.1 on 2025-06-01 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_stockitem_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='supplier',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fornecedor'),
        ),
    ]
