# Generated by Django 5.2.1 on 2025-06-05 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_supplier_alter_stockitem_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome que aparecerá para o cliente. Pode ser diferente do nome no estoque.', max_length=100, verbose_name='Nome no Cardápio')),
                ('description', models.TextField(blank=True, help_text='Uma breve descrição do produto para o cardápio.', null=True, verbose_name='Descrição do Produto')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço de Venda')),
                ('image', models.ImageField(blank=True, help_text='Foto específica para o cardápio. Se deixado em branco, pode-se usar a foto do item de estoque.', null=True, upload_to='menu_product_images/', verbose_name='Foto no Cardápio')),
                ('is_active', models.BooleanField(default=True, help_text='Marque se este produto deve aparecer no cardápio para os clientes.', verbose_name='Ativo no Cardápio?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock_item', models.ForeignKey(help_text='Selecione o item do estoque que será a base para este produto do cardápio.', on_delete=django.db.models.deletion.CASCADE, to='stock.stockitem', verbose_name='Item de Estoque de Origem')),
            ],
            options={
                'verbose_name': 'Produto do Cardápio',
                'verbose_name_plural': 'Produtos do Cardápio',
                'ordering': ['name'],
            },
        ),
    ]
