# Generated by Django 5.2.1 on 2025-06-12 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_menuproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='cnpj_cpf',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='CNPJ/CPF'),
        ),
    ]
