# Generated by Django 5.2.1 on 2025-06-14 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_supplier_city_supplier_neighborhood_supplier_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='profit_percentage',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text='Percentual de lucro a ser aplicado sobre o preço de custo para sugerir o preço de venda.', max_digits=5, verbose_name='Margem de Lucro (%)'),
        ),
    ]
