# Generated by Django 5.2.1 on 2025-06-14 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='payment_method',
            field=models.CharField(choices=[('NA_RETIRADA', 'Pagar na Retirada'), ('ONLINE', 'Pago Online')], default='NA_RETIRADA', max_length=20, verbose_name='Método de Pagamento'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='status',
            field=models.CharField(choices=[('AGUARDANDO', 'Aguardando'), ('PAGO', 'Pago'), ('EM_PREPARO', 'Em Preparo'), ('PRONTO', 'Pronto para Retirada'), ('FINALIZADO', 'Finalizado/Entregue'), ('CANCELADO', 'Cancelado')], default='AGUARDANDO', max_length=20, verbose_name='Status'),
        ),
    ]
