# Generated by Django 5.2.1 on 2025-06-14 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_venda_payment_method_alter_venda_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='status',
            field=models.CharField(choices=[('AGUARDANDO_PAGAMENTO', 'Aguardando Pagamento'), ('PAGO', 'Pago'), ('EM_PREPARO', 'Em Preparo'), ('PRONTO', 'Pronto para Retirada'), ('FINALIZADO', 'Finalizado/Entregue'), ('CANCELADO', 'Cancelado')], default='AGUARDANDO_PAGAMENTO', max_length=25, verbose_name='Status'),
        ),
    ]
