# Generated by Django 5.2.1 on 2025-06-15 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_venda_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemvenda',
            name='subtotal',
        ),
        migrations.AlterField(
            model_name='venda',
            name='payment_method',
            field=models.CharField(choices=[('NA_RETIRADA', 'Pagar na Retirada'), ('ONLINE', 'Pago Online'), ('DINHEIRO', 'Dinheiro'), ('CARTAO_DEBITO', 'Cartão de Débito'), ('CARTAO_CREDITO', 'Cartão de Crédito'), ('PIX', 'Pix')], default='DINHEIRO', max_length=20, verbose_name='Método de Pagamento'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='status',
            field=models.CharField(choices=[('AGUARDANDO_PAGAMENTO', 'Aguardando Pagamento'), ('PAGO', 'Pago'), ('EM_PREPARO', 'Em Preparo'), ('PRONTO', 'Pronto para Retirada'), ('FINALIZADO', 'Finalizado/Entregue'), ('CANCELADO', 'Cancelado')], default='PAGO', max_length=25, verbose_name='Status'),
        ),
    ]
